package com.artpizza.model;

public enum EstadoConversa {
    MENU,
    ESCOLHENDO_TAMANHO,
    ESCOLHENDO_SABORES,
    OBSERVACAO,
    PERGUNTANDO_MAIS_ITEM,
    ESCOLHENDO_PRODUTO,
    ESCOLHENDO_QUANTIDADE_PRODUTO,
    TIPO_ENTREGA,
    ENDERECO_BAIRRO,
    ENDERECO_RUA,
    ENDERECO_NUMERO,
    FORMA_PAGAMENTO,
    CONFIRMACAO
}
